name: Java CI with Gradle

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job that runs the tests
jobs:
  build:
    # Set the runner environment to use the latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Build the project and run tests using Gradle (you can change it to Maven if you're using Maven)
      - name: Build and Test with Gradle
        run: |
          ./gradlew build test

      # Optionally, you can add a step to display the results of the tests
      - name: Display Test Results
        run: |
          cat build/test-logs/test.log  # Adjust the path based on where your test logs are saved
